In [2]:
import numpy as np
import pandas as pd

In [90]:
m1 = 1
m2 = 2
positions = [[5, 6], [1, 2]] # 2 masses in this case
masses = [m1, m2]

def quadrupole_moment(masses, positions):
    """ 
    Calculate the 2D quadrupole moment for a pair of masses (masses = [m1, m2]). 
    
    Insert data as list of masses and positions (positions = [[x1, y1], [x2, y2]]) 
    """
    Q = np.zeros((2,2)) # 2x2 matrix for quadrupole moment tensor in 2D
    data = zip(masses, positions) # data = [(m1, [x1, y1]), (m2, [x2, y2])]
    for mass, pos in data:
        pos = np.array(pos)
        R = np.dot(pos, pos) # R = [x^2 + y^2 for given m]
    for i in range(2):
        for j in range(2):
            Q[i, j] += mass * (3 * pos[i] * pos[j] - (R if i == j else 0))
    return Q
Q

array([[26.,  0.],
       [ 0., 26.]])

In [102]:
m1 = 1
m2 = 2
positions = [[5, 6], [1, 2]] 
masses = [m1, m2]
def quadrupole_moment(masses, positions):
    """ 
    Calculate the 2D quadrupole moment for a pair of masses (masses = [m1, m2]). 
    Insert data as list of masses and positions (positions = [[x1, y1], [x2, y2]]) 
    """
    Q = np.zeros((2, 2))  # 2x2 matrix for quadrupole moment tensor in 2D
    data = zip(masses, positions)  # data = [(m1, [x1, y1]), (m2, [x2, y2])]
    
    for mass, pos in data:  # Iterate over each mass and position
        pos = np.array(pos)
        R = np.dot(pos, pos)  # R = x^2 + y^2 for current mass and position
        
        # Now iterate over i and j to update the Q tensor for the current mass
        for i in range(2):
            for j in range(2):
                Q[i, j] += mass * (3 * pos[i] * pos[j] - (R if i == j else 0))
    
    return Q
print(quadrupole_moment(masses, positions))

[[ 10. 102.]
 [102.  61.]]


In [100]:
m1 = 1
m2 = 2
positions = [[5, 6], [1, 2]] 
masses = [m1, m2]
quadrupole_moment(masses, positions)

array([[ 10., 102.],
       [102.,  61.]])

In [68]:
help(quadrupole_moment)

Help on function quadrupole_moment in module __main__:

quadrupole_moment(masses, positions)
    Calculate the 2D quadrupole moment for a pair of masses.



In [78]:
def qdrpl_trajectory(masses, trajectories):
    """
    Find the quadrupole moment at each point in the 2D trajectory of two masses.
    
    Insert data as list of masses [m1, m2] and trajectories, with list of trajectories being a list of positions for each mass [[x1, y1], [x2, y2], ...]
    
    Outputs a list of quadrupole moment tensors (2x2) at each position / time step
    """
    # Time step N
    time_n = len(trajectories[0])
    
    quadrupole_moments = []
    
    for t in range(time_n):
        # Get positions of all masses at time step t
        pos_t = [trajectory[t] for trajectory in trajectories]
        
        # Calculate the quadrupole moment for this time step
        Q_t = quadrupole_moment(masses, pos_t)
        
        # Append the quadrupole moment tensor to the list
        quadrupole_moments.append(Q_t)
    
    return quadrupole_moments

# Example data for 2 masses and their trajectories
m1 = 1
m2 = 2
masses = [m1, m2]

# Trajectories: each sublist is the trajectory of a mass over 3 time steps
trajectories = [
    [[5, 6], [6, 7], [7, 8]],  # Trajectory of mass 1 (at times t1, t2, t3)
    [[1, 2], [2, 3], [3, 4]]   # Trajectory of mass 2 (at times t1, t2, t3)
]

# Calculate the quadrupole moment at each point of the trajectory
quadrupole_moments = qdrpl_trajectory(masses, trajectories)

# for exporting data use list(quadrupole_moments), for dispaying use enumerate(quadrupole moments)
for t, Q_t in enumerate(quadrupole_moments):
    print(f"Quadrupole Moment Tensor at time t{t+1}:")
    print(Q_t)
    print()

Quadrupole Moment Tensor at time t1:
[[-4. 12.]
 [12. 14.]]

Quadrupole Moment Tensor at time t2:
[[-2. 36.]
 [36. 28.]]

Quadrupole Moment Tensor at time t3:
[[ 4. 72.]
 [72. 46.]]



In [76]:
list(enumerate(quadrupole_moments))

[(0,
  array([[-4., 12.],
         [12., 14.]])),
 (1,
  array([[-2., 36.],
         [36., 28.]])),
 (2,
  array([[ 4., 72.],
         [72., 46.]]))]

In [79]:
list(quadrupole_moments)

[array([[-4., 12.],
        [12., 14.]]),
 array([[-2., 36.],
        [36., 28.]]),
 array([[ 4., 72.],
        [72., 46.]])]